// <auto-generated />
namespace exemploasp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tabelas_disp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tabelas_disp));
        
        string IMigrationMetadata.Id
        {
            get { return "201801291935396_tabelas_disp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
