// <auto-generated />
namespace exemploasp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Exposicoes_Temas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Exposicoes_Temas));
        
        string IMigrationMetadata.Id
        {
            get { return "201801111755337_Exposicoes_Temas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
